spring:
  application:
    name: "hotel-management"

  datasource:
    url: jdbc:mysql://database-1.cji8u4ycew1l.ap-southeast-1.rds.amazonaws.com:3306/hotel_management_db?createDatabaseIfNotExist=true
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      issuer : "ByteSync Solution"
      secret-key: "344dc71229be8fc466048b20963d73568147dd94683891151a15957ef4e1b589"
      access: 600
      refresh: 1440

server:
  port: 9090

