spring:
  application:
    name: "hotel-management"

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management_db?createDatabaseIfNotExist=true
    username: root
    password: admin
#    url: jdbc:mysql://database-1.cji8u4ycew1l.ap-southeast-1.rds.amazonaws.com:3306/hotel_management_db?createDatabaseIfNotExist=true
#    username: admin
#    password: admin123
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      issuer : "ByteSync Solution"
      secret-key: "344dc71229be8fc466048b20963d73568147dd94683891151a15957ef4e1b589"
      access: 1440
      refresh: 4320

server:
  port: 9090
  address: 127.0.0.1
  forward-headers-strategy: framework

aws:
  s3:
    bucket: "chanmyae-hotel"
    region: "ap-southeast-1"
    access-key: ""
    secret-key: ""

